### ISSUE TITLE
From state isn't checked in the transition.

### ISSUE THREAD

**Issue by elburgl69** [szana8/laraflow#14]
A transition does not check if the current state is the 'from' strate defined by the configuration. 

fe. $model->current_state = 3

$configuration = [
   ...
  'transitions' => [
     'makeInvoice' => [
        'from' => 7,
        'to' => 8,
         ...
    ]
    ...
  ],
  ...
];

$model->transition('makeInvoice');
will set $model->current_state to 8, without warning or exception.

Is was thinking to fix this like:
try {
   $model->transition('makeInvoice')  // will throw an error if state doesn't match 'from'
} catch (\Throwable $th) {
    if ($force_transition) {
      $model->force_ransition('makeInvoice')
    } else
    {
      throw $th;
    }
}

**Comment by szana8** [comment]
There is a check in the can funtion:
if (collect($this->configuration['transitions'])->where('from', $this->getActualStep())->count() == 0) {
            return false;
        }
I will replace the count function to isEmpty so no need to check the zero count.

**Comment by szana8** [comment]
Sorry my bad. I updated the can function and add this line to the code:
        if ($this->configuration['transitions'][$transition]['from'] != $this->getActualStep()) {
            throw new LaraflowException(__('laraflow::exception.invalid_transition', ['transition' => $transition]));
        }

Now it checks the from is the correct step which is in the transition what we want to do.

**Comment by elburgl69** [comment]
Nice thanks.
