### ISSUE TITLE
Problem on publish sources in laravel 8

### ISSUE THREAD

**Issue by aramhuseiny** [szana8/laraflow#20]
Hi every one
I found a bug in the package while I tried to publish the contents.
I'm on laravel 8 an try to test the laralflow codes. 
On publishing sources I get this error: 
`"Can't locate path: </PathToApp/szana-workflow/vendor/szana8/laraflow/src./config/laraflow.php>"
`
I checked the source and found this :

`$this->publishes([
            __DIR__.'./config/laraflow.php' => config_path('laraflow.php'),
        ], 'config');`

Problem will be fix by remove DOT before "/config".

**Comment by szana8** [comment]
Thanks to identify the issue @aramhuseiny. I fixed that in the latest release.
