### ISSUE TITLE
Missing action update

### ISSUE THREAD

**Issue by ext-rgonzalez** [szana8/laraflow#22]
hi am working with this package and it is great but, when i try to update the status in the users table this does not work because the transaction is missing apply.

https://github.com/szana8/laraflow/blob/e0c7e7508e10e93ddd8c70fbe33e81987e30db6d/src/Laraflow.php#L168

$this->object->setAttribute($this->configuration['property_path'], $step)->update();

**Comment by szana8** [comment]
Hi,

Can you send me how do you call this? Because if you use the the trait transition method it should apply the changes
`public function transition($transition, $sm_name = 'default')
    {
        return $this->laraflowInstance($sm_name)->apply($transition);
    }`
