### ISSUE TITLE
how to load config from  database

### ISSUE THREAD

**Issue by baihaqyaviq** [szana8/laraflow#4]
how to load config from database for state complex

**Comment by szana8** [comment]
Hi @baihaqyaviq ,

Sorry for the late response. To load a config from a database you need a table and a model in Laravel which stores them first. For example lets called workflow. The table has a column which has to be json or char/text type. You have to store the json string of the workflow here.
The next step is you have to connect your model which use the workflow to the workflow model. In this model you have to use the Flowable trait and this model have to implement the getLaraflowStates() function. This function has to return the json string of the workflow.
You can do it like this:
public function workflow()
{
   return $this->hasOne(Workflow::class);
}

/**
     * Return the workflow configuration array
     *
     * @return array
     */
    public function getLaraflowStates()
    {
        return $this->workflow()->workflow;
    }
