### ISSUE TITLE
Laravel 5.5 not supported.

### ISSUE THREAD

**Issue by elburgl69** [szana8/laraflow#7]
When requiring the stable package in Laravel 5.5.* project, composer fails.

Composer.json has to change to include the 5.5.* illuminate/database:
` "illuminate/database":` "5.5.* || 5.6.* || 5.7.* || 6.*"

**Comment by szana8** [comment]
Thanks, I updated the composer json in the development branch. I will update the stable version soon.

**Comment by szana8** [comment]
The 0.15 contains the Laravel 5.5 support.
