### ISSUE TITLE
Multiple stat machines in 1 model

### ISSUE THREAD

**Issue by elburgl69** [szana8/laraflow#8]
Do you plan to support multiple states in 1 model? 

fe. 
preperation_state
delivery_state

**Comment by szana8** [comment]
Hi,

Interesting idea. I can take a look how can I implement this feature and I will let you know the answer.

Thanks ,
Istvan

**Comment by elburgl69** [comment]
Hi,

Needed it, so implmented it myself. From an user perspective you only have change the exiting config array to the form:
```php
[
  'default' => [
     //... the configuration array as we know it.
  ],
  // for a second state machine:
  'second_state' => [
    //... the configuration array as we know it.
  ]
];
```

It basically saves the LaraFlow instances in an array on the model (all in Flowable.php). Most Flowable.php methods now have changed to:
```php
public function getToStepNameById($stateId, $sm_name = 'default')
{
    // ...
}
```
laraflowInstance($sm_name = 'default') will get the correct instance.

You call the transition as is for exiting cases or as:
```php
$model->transition($newState, 'stateMachineName');
```

If you are intrested i can create a pull request. Please let me know on which branch you want it.

**Comment by szana8** [comment]
Hi,

Thanks. It would be good to create a pull request. I've created a multiple_state_feature_dev branch for the pull request. I've also added some small development to the master and release a new version 0.16.
I am also working on a front end package of these https://github.com/szana8/laraflow-go so you can edit your workflow in a UI. It still need some improvement and readme refresh but I have a fulltime job so I need more time to finish these.

**Comment by elburgl69** [comment]
Hi,

Made the pull request. Tomorrow morning I have some time to rebase my work on v0.16. So to save time, you can wait for my next pull request tommorow. 

My use case is not to have a front end. I now needed a light package to have a uniform state management API on my models. My current customers (small businesses) have no knowledge to manage workflows, but perhaps in the future.

rg,
Leo

**Comment by szana8** [comment]
Merged the pull request to the master. Thanks for the help.
